apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ulla
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0066-tenant/cin4s-839-0066-app/devfile-sample-ulla@sha256:ca5121e7dbdd09419910bc51899919b5dc7091556b5c6c45436909634a35ccb7
        name: my-nodejs
        resources: {}
status: {}
